#properties
server:
  error:
    include-stacktrace: never
  port: 80
spring:
   servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1 
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
   ReadTimeout: 30000
   connection-timeout: 30000
zuul:
   sensitive-headers:
   - Cookie
   - Set-Cookie
   host:
    connect-timeout-millis: 62000
    socket-timeout-millis: 62000
   routes:
    scotiathon-client-service:
     url: SCOTIATHON-CLIENT-SERVICE
     path: /client-service/**
    scotiathon-auth-service:
     url: SCOTIATHON-AUTH-SERVICE
     path: /oauth-service/**
    scotiathon-voucher-service:
     url: SCOTIATHON-VOUCHER-SERVICE
     path: /voucher-service/**
    
#security
auth:
  white:
    list: /client-service/clients/login,/oauth-service/oauth/token,/healthy,/actuator/refresh,/**/swagger-ui.html,/**/v2/api-docs,/**/swagger-resources/**,/**/webjars/springfox-swagger-ui/*
  deny:
    list: /client-service/clients/details
  supervisor: 
    list: /voucher-service/vouchers,/voucher-service/vouchers/exclusions
    
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

